#el servidor muestra los errores
#customizados en la carpeta error
#Error 404: no se encuentra la pagina
#Error 500: Error de programacion en back-end
server:
  error: 
    whitelabel:
          enabled: false

#configuracion de base de datos
#nombre bd: base_emanon
#password db: emanonpass          
spring:
  datasource:    url: jdbc:mysql://localhost:3306/base_emanon?useSSL=false&useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    username: root
    password: emanonpass  jpa:    show-sql: true
    hibernate:      ddl-auto: update      